export const apartment = {
    GET_APARTMENTS: "GET_APARTMENTS",
    ADD_APARTMENT: "ADD_APARTMENT",
    EDIT_APARTMENT: "EDIT_APARTMENT",
    REMOVE_APARTMENT: "REMOVE_APARTMENT"
};

export const errors = {
    ADD_ERROR: "ADD_ERROR",
    ADD_ERRORS: "ADD_ERRORS",
    FLUSH_ERRORS: "FLUSH_ERRORS",
};